# Generated by Django 4.2.11 on 2024-05-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendoraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='NID',
            new_name='NID_number',
        ),
    ]
