# Generated by Django 4.2.11 on 2024-05-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorAccount',
        ),
    ]
