# Generated by Django 4.2.11 on 2024-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_billingaddress_division_billingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='last_name',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
