# Generated by Django 4.2.11 on 2024-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_billingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='city',
            new_name='district',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='police_station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
