# Generated by Django 4.2.11 on 2024-05-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_alter_fruitmodel_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='vendor_name',
        ),
    ]
