# Generated by Django 4.2.11 on 2024-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0004_rename_name_vendor_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
