# Generated by Django 4.2.11 on 2024-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0005_alter_fruitmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
