# Generated by Django 4.2.11 on 2024-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0006_alter_fruitmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitmodel',
            name='flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fruitmodel',
            name='stocked_out',
            field=models.BooleanField(default=False),
        ),
    ]
