# Generated by Django 4.2.11 on 2024-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0008_favouritefruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
