# Generated by Django 4.2.11 on 2024-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0009_alter_fruitmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
