# Generated by Django 4.2.11 on 2024-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitmodel',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='fruitmodel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruitmodel',
            name='supply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
