# Generated by Django 4.2.11 on 2024-05-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0013_remove_fruitmodel_timestamp_fruitmodel_expiry_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteFruit',
        ),
    ]
