# Generated by Django 4.2.11 on 2024-06-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0014_delete_favouritefruit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='review',
        ),
    ]
