# Generated by Django 3.2.25 on 2024-06-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0017_fruitmodel_blockchain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitmodel',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
