# Generated by Django 4.2.11 on 2024-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('In Processing', 'In Processing'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='In Queue', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('SSLCOMMERZ', 'SSLCOMMERZ')], max_length=30),
        ),
    ]
