# Generated by Django 4.2.11 on 2024-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('In Processing', 'In Processing'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='In Queue', max_length=30),
        ),
    ]
