# Generated by Django 4.2.11 on 2024-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cart_updated_cart_removed_from_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='removed_from_view',
        ),
        migrations.AddField(
            model_name='order',
            name='removed_from_view',
            field=models.BooleanField(default=False),
        ),
    ]
